create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text,
  created_at timestamptz default now()
);

create table if not exists public.contributors (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  role text,
  message text,
  created_at timestamptz default now()
);

create table if not exists public.donors (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  amount text,
  message text,
  created_at timestamptz default now()
);

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  name text,
  email text not null,
  created_at timestamptz default now()
);
